vtk_module(vtkRenderingCore
  DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonExecutionModel
    vtkCommonMath
    vtkCommonMisc
    vtkCommonSystem
    vtkCommonTransforms
    vtkCommonComputationalGeometry
    vtkFiltersCore
    vtkFiltersSources
    vtkFiltersGeneral
    vtkFiltersGeometry
    vtkFiltersExtraction
    vtkIOImage
    vtkIOXML
    #vtkInteractionSelection
  DEFAULT ON)
